uncomment yml line 15_16

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,16 +4,16 @@ on: push
 
 jobs:
   build:
-    #runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
 
-    #steps:
+    steps:
       - uses: actions/checkout@v2
 
       - name: Run a one-line script
         run: echo "Hello, CI/CD!"
 
-      #- name: Simulate an error
-      #  run: echo "About to fail" ; exit 1
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
 
       - name: Another greeting
         run: echo "Hello, CI/CD again!"
